servers:
  R1:
    name: R1
    interfaces:
      ens36:
        address: 111.100.100.2
        netmask: 24
        conn_name: "Wired connection 1"
      ens37:
        address: 100.100.100.1
        netmask: 26
        conn_name: "Wired connection 2"
    apt_R1:
      - network-manager
      - isc-dhcp-server
      - radvd
      - frr
      - strongswan
      - chrony
      - iperf3
      - nfs-common
      - firewalld
      - iptables-persistent
  PC_R1:
    name: PC-R1
    apt_PC_R1:
      - network-manager
      - bind9
      - chrony
      - clamav
      - nfs-kernel-server
      - nfs-common
      - cups
      - firewalld
      - iptables-persistent
  R2:
    name: R2
    interfaces:
      ens36:
        address: 222.100.100.2
        netmask: 24
        conn_name: "Wired connection 1"
      ens37:
        address: 200.200.200.1
        netmask: 28
        conn_name: "Wired connection 2"
    apt_R2:
      - network-manager
      - frr
      - strongswan
      - chrony
      - nfs-common
      - firewalld
      - iptables-persistent
  PC_R2:
    name: PC-R2
    apt_PC_R2:
      - network-manager
      - chrony
      - clamav
      - nfs-common
      - firewalld
      - iptables-persistent
  R0:
    name: R0
    interfaces:
      ens36:
        address: 111.100.100.1
        netmask: 24
        conn_name: "Wired connection 1"
      ens37:
        address: 222.100.100.1
        netmask: 24
        conn_name: "Wired connection 2"
    apt_R0:
      - network-manager
      - chrony
      - firewalld
      - iptables-persistent
