galaxy_info:
  role_name: package_installation
  description: Установка необходимых пакетов на VM
  author: Magomedov M. (https://github.com/reader2k24)
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - all
