include:
  - local: 'gitlab-ci/ci-templates.yml'

stages:
  - install_packages
  - notify_packages
  - install_ip
  - notify_ip


# Установка пакетов
.install_package_r_template:
  extends: .install_package_template
  variables:
    PLAYBOOK_INDEX: $PLAYBOOK_INDEX_PACKAGE

install_package_r1:
  extends: .install_package_r_template
  variables:
    SERVER_LIMIT: 'r1_server'
  tags:
    - r1.server

install_package_pc_r1:
  extends: .install_package_r_template
  variables:
    SERVER_LIMIT: 'r1_pc'
  tags:
    - pc-r1.server

install_package_r2:
  extends: .install_package_r_template
  variables:
    SERVER_LIMIT: 'r2_server'
  tags:
    - r2.server

install_package_pc_r2:
  extends: .install_package_r_template
  variables:
    SERVER_LIMIT: 'r2_pc'
  tags:
    - pc-r2.server

install_package_r0:
  extends: .install_package_r_template
  variables:
    SERVER_LIMIT: 'r0_server'
  tags:
    - r0.server

# Уведомление после установки пакетов
notify_packages:
  extends: .notify_template
  variables:
    PLAYBOOK_INDEX: "1"
  needs:
    - install_package_r1
    - install_package_pc_r1
    - install_package_r2
    - install_package_pc_r2
    - install_package_r0

# Установка IP
.install_ip_r_template:
  extends: .install_package_ip_template
  variables:
    PLAYBOOK_INDEX: $PLAYBOOK_INDEX_IP

install_ip_r1:
  extends: .install_ip_r_template
  variables:
    SERVER_LIMIT: 'r1_server'
  tags:
    - r1.server
  needs:
    - install_package_r1

install_ip_pc_r1:
  extends: .install_ip_r_template
  variables:
    SERVER_LIMIT: 'r1_pc'
  tags:
    - pc-r1.server
  needs:
    - install_package_pc_r1

install_ip_r2:
  extends: .install_ip_r_template
  variables:
    SERVER_LIMIT: 'r2_server'
  tags:
    - r2.server
  needs:
    - install_package_r2

install_ip_pc_r2:
  extends: .install_ip_r_template
  variables:
    SERVER_LIMIT: 'r2_pc'
  tags:
    - pc-r2.server
  needs:
    - install_package_pc_r2

install_ip_r0:
  extends: .install_ip_r_template
  variables:
    SERVER_LIMIT: 'r0_server'
  tags:
    - r0.server
  needs:
    - install_package_r0

# Уведомление после установки IP
notify_ip:
  extends: .notify_template
  variables:
    PLAYBOOK_INDEX: "2"
  needs:
    - install_ip_r1
    - install_ip_pc_r1
    - install_ip_r2
    - install_ip_pc_r2
    - install_ip_r0
  when: always
